version: 2.1

jobs:
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke_test
          command: |
            URL="https://blog.udacity.com/"
            if curl -s --head ${URL} #test if blog.udacity.com exists
            then
              return 0
            else
              return 1
            fi
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["fe:61:cc:11:26:35:2d:e1:44:bf:76:5c:bd:51:b8:74"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible && apk add openssh # install the dependencies needed for your playbook
      - run:
          name: Fix host authenticity for inventory
          command: |
            ssh-keyscan 54.245.77.184 >> ~/.ssh/known_hosts
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory main-remote.yml


workflows:
  my_workflow:
    jobs:
      - smoke_test:
          requires:
            - configure_infrastructure
